import 'language_service.dart';

class AppStrings {
  static final Map<String, Map<String, String>> _tr = {
    'ar': {
      // ── عام ──
      'app_name': 'MotionHR',
      'login': 'دخول',
      'logout': 'تسجيل الخروج',
      'username': 'اسم المستخدم',
      'password': 'كلمة المرور',
      'remember_me': 'تذكرني',
      'stay_logged_in': 'البقاء مسجلاً',
      'forgot_password': 'نسيت كلمة المرور؟',
      'welcome': 'مرحباً بك، سجل دخولك للمتابعة',
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'confirm': 'تأكيد',
      'delete': 'حذف',
      'edit': 'تعديل',
      'add': 'إضافة',
      'search': 'بحث',
      'refresh': 'تحديث',
      'loading': 'جاري التحميل...',
      'error': 'خطأ',
      'success': 'تم بنجاح',
      'no_data': 'لا توجد بيانات',
      'language': 'اللغة',
      'settings': 'الإعدادات',
      'change_language': 'تغيير اللغة',
      'yes': 'نعم',
      'no': 'لا',
      'ok': 'حسناً',
      'back': 'رجوع',
      'close': 'إغلاق',
      'send': 'إرسال',
      'retry': 'إعادة المحاولة',
      'select': 'اختر',
      'all': 'الكل',
      'submit': 'إرسال',
      'next': 'التالي',
      'previous': 'السابق',
      'done': 'تم',
      'skip': 'تخطي',
      'choose_language': 'اختر لغتك',
      'choose_language_desc': 'اختر اللغة المفضلة لديك لاستخدام التطبيق',
      'arabic': 'العربية',
      'english': 'English',
      'continue': 'متابعة',

      // ── تسجيل الدخول ──
      'login_biometric': 'دخول بالبصمة',
      'login_error': 'بيانات الدخول غير صحيحة',
      'connection_error': 'خطأ في الاتصال بالخادم',
      'enter_username_password': 'من فضلك ادخل اسم المستخدم وكلمة المرور',
      'stay_logged_in_desc': 'يبقى الحساب مفتوحاً حتى 72 ساعة أو حتى تسجيل الخروج',
      'forgot_password_desc': 'من فضلك تواصل مع مسئول الموارد البشرية لإعادة تعيين كلمة المرور الخاصة بك.',

      // ── داشبورد ──
      'dashboard': 'لوحة التحكم',
      'quick_management': 'الإدارة السريعة',
      'tools': 'الأدوات',
      'pending_requests': 'الطلبات المعلقة',
      'attendance_today': 'الحضور اليوم',
      'field_workers': 'الموظفون الميدانيون',
      'live_locations': 'المواقع المباشرة',
      'employees': 'الموظفون',
      'add_employee': 'إضافة موظف',
      'announcements': 'الإعلانات',
      'reports': 'التقارير',
      'payroll': 'الرواتب',
      'reminders': 'التذكيرات',
      'company_charter': 'لائحة الشركة',
      'geofence': 'نطاق الجيو',
      'missions': 'المهمات',
      'company_info': 'بيانات الشركة',
      'org_tree': 'الهيكل التنظيمي',
      'location_report': 'تقرير المواقع',

      // ── الحضور ──
      'check_in': 'تسجيل الحضور',
      'check_out': 'تسجيل الانصراف',
      'checked_in': 'تم الحضور',
      'checked_out': 'تم الانصراف',
      'check_in_time': 'وقت الحضور',
      'check_out_time': 'وقت الانصراف',
      'shift': 'الشيفت',
      'remaining_time': 'الوقت المتبقي',
      'shift_ended': 'الشيفت خلص، تقدر تنصرف',
      'history': 'سجل الأيام السابقة',
      'today': 'اليوم',
      'date': 'التاريخ',
      'time': 'الوقت',
      'early_leave_permission': 'عندك إذن خروج مبكر',
      'attendance_done': 'تم تسجيل الحضور والانصراف',
      'great_work': 'أحسنت العمل اليوم 👏',

      // ── الموظف ──
      'employee_code': 'الرقم الوظيفي',
      'full_name': 'الاسم الكامل',
      'first_name': 'الاسم الأول',
      'last_name': 'الاسم الأخير',
      'middle_name': 'الاسم الأوسط',
      'first_name_ar': 'الاسم الأول بالعربي',
      'last_name_ar': 'الاسم الأخير بالعربي',
      'first_name_en': 'الاسم الأول بالإنجليزي',
      'last_name_en': 'الاسم الأخير بالإنجليزي',
      'phone': 'الموبايل',
      'email': 'البريد الإلكتروني',
      'national_id': 'الرقم القومي',
      'birth_date': 'تاريخ الميلاد',
      'gender': 'النوع',
      'male': 'ذكر',
      'female': 'أنثى',
      'address': 'العنوان',
      'branch': 'الفرع',
      'department': 'الإدارة',
      'job_title': 'المسمى الوظيفي',
      'direct_manager': 'المدير المباشر',
      'hire_date': 'تاريخ التعيين',
      'basic_salary': 'الراتب الأساسي',
      'reset_password': 'إعادة تعيين كلمة المرور',
      'create_employee': 'إنشاء موظف',
      'edit_employee': 'تعديل بيانات الموظف',
      'employee_details': 'تفاصيل الموظف',
      'transfer_employee': 'نقل الموظف',
      'employees_list': 'قائمة الموظفين',
      'no_employees': 'لا يوجد موظفون',

      // ── الحالات ──
      'active': 'نشط',
      'on_leave': 'في إجازة',
      'suspended': 'موقوف',
      'resigned': 'مستقيل',
      'terminated': 'مفصول',
      'required': 'مطلوب',
      'pending': 'في الانتظار',
      'approved': 'موافق عليه',
      'rejected': 'مرفوض',
      'cancelled': 'ملغي',
      'in_progress': 'جارية',
      'completed': 'مكتملة',

      // ── الطلبات والإجازات ──
      'requests': 'الطلبات',
      'leaves': 'الإجازات',
      'my_requests': 'طلباتي',
      'my_leaves': 'إجازاتي',
      'submit_request': 'تقديم طلب',
      'request_type': 'نوع الطلب',
      'leave_type': 'نوع الإجازة',
      'request_title': 'عنوان الطلب',
      'request_details': 'التفاصيل',
      'from_date': 'من تاريخ',
      'to_date': 'إلى تاريخ',
      'reason': 'السبب',
      'cancel_request': 'إلغاء الطلب',
      'cancel_request_confirm': 'هل أنت متأكد من إلغاء هذا الطلب؟',
      'cancel_reason': 'سبب الإلغاء (اختياري)',
      'no_requests': 'لا يوجد طلبات',
      'request_leave': 'طلب إجازة',
      'leave_balance': 'الرصيد المتبقي',
      'days': 'يوم',
      'hours': 'ساعة',
      'amount': 'المبلغ',

      // ── المهمات ──
      'mission': 'مهمة',
      'missions_list': 'قائمة المهمات',
      'create_mission': 'إنشاء مهمة جديدة',
      'mission_title': 'عنوان المهمة',
      'mission_details': 'تفاصيل المهمة',
      'mission_location': 'موقع المهمة',
      'client_name': 'اسم العميل',
      'client_phone': 'تليفون العميل',
      'priority': 'الأولوية',
      'urgent': 'عاجل',
      'high': 'عالي',
      'normal': 'عادي',
      'planned_start': 'وقت البدء المخطط',
      'planned_end': 'وقت الانتهاء المخطط',
      'start_mission': 'بدء المهمة',
      'end_mission': 'إنهاء المهمة',
      'accept_mission': 'قبول',
      'reject_mission': 'رفض',
      'my_missions': 'مهماتي',
      'no_missions': 'لا توجد مهمات',
      'mission_feedback': 'فيدباك الزيارة',
      'write_feedback': 'كتابة الفيدباك',
      'interest_rating': 'تقييم اهتمام العميل',
      'deal_probability': 'احتمال الصفقة',
      'client_status': 'حالة العميل',
      'very_interested': 'مهتم جداً',
      'interested': 'مهتم',
      'thinking': 'يفكر',
      'not_interested': 'غير مهتم',
      'postponed': 'مؤجل',
      'needs_followup': 'يحتاج متابعة',
      'contract_signed': 'تم توقيع عقد',
      'participants': 'المشاركون',
      'mission_lead': 'قائد المهمة',
      'withdraw_request': 'طلب الانسحاب',
      'withdraw_reason': 'سبب الانسحاب',

      // ── الإشعارات ──
      'notifications': 'الإشعارات',
      'no_notifications': 'لا توجد إشعارات',
      'mark_all_read': 'تعليم الكل كمقروءة',
      'now': 'الآن',
      'minutes_ago': 'منذ {n} دقيقة',
      'hours_ago': 'منذ {n} ساعة',
      'days_ago': 'منذ {n} يوم',

      // ── الإعدادات ──
      'profile': 'الملف الشخصي',
      'change_password': 'تغيير كلمة المرور',
      'current_password': 'كلمة المرور الحالية',
      'new_password': 'كلمة المرور الجديدة',
      'confirm_password': 'تأكيد كلمة المرور',
      'password_changed': 'تم تغيير كلمة المرور بنجاح',
      'password_mismatch': 'كلمة المرور غير متطابقة',
      'password_too_short': 'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
      'biometric_login': 'الدخول بالبصمة',
      'biometric_confirm': 'تأكيد تفعيل الدخول بالبصمة',
      'biometric_prompt': 'سجّل دخولك بالبصمة',

      // ── الشركة ──
      'company': 'الشركة',
      'company_name': 'اسم الشركة',
      'company_info': 'بيانات الشركة',
      'company_logo': 'شعار الشركة',
      'company_address': 'عنوان الشركة',
      'company_phone': 'تليفون الشركة',
      'company_email': 'إيميل الشركة',
      'branches': 'الفروع',
      'departments': 'الإدارات',
      'managers': 'المديرون',
      'upload_logo': 'رفع الشعار',
      'edit_company': 'تعديل بيانات الشركة',

      // ── التقارير ──
      'attendance_report': 'تقرير الحضور',
      'leaves_report': 'تقرير الإجازات',
      'late_report': 'تقرير التأخيرات',
      'absence_report': 'تقرير الغياب',
      'work_hours_report': 'تقرير ساعات العمل',
      'requests_report': 'تقرير الطلبات',
      'location_report': 'تقرير المواقع',
      'export_pdf': 'تصدير PDF',
      'export_excel': 'تصدير Excel',
      'print': 'طباعة',
      'powered_by': 'Powered by MotionHR - JS Solutions',
    },

    'en': {
      // ── General ──
      'app_name': 'MotionHR',
      'login': 'Login',
      'logout': 'Logout',
      'username': 'Username',
      'password': 'Password',
      'remember_me': 'Remember me',
      'stay_logged_in': 'Stay logged in',
      'forgot_password': 'Forgot password?',
      'welcome': 'Welcome, sign in to continue',
      'save': 'Save',
      'cancel': 'Cancel',
      'confirm': 'Confirm',
      'delete': 'Delete',
      'edit': 'Edit',
      'add': 'Add',
      'search': 'Search',
      'refresh': 'Refresh',
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      'no_data': 'No data',
      'language': 'Language',
      'settings': 'Settings',
      'change_language': 'Change Language',
      'yes': 'Yes',
      'no': 'No',
      'ok': 'OK',
      'back': 'Back',
      'close': 'Close',
      'send': 'Send',
      'retry': 'Retry',
      'select': 'Select',
      'all': 'All',
      'submit': 'Submit',
      'next': 'Next',
      'previous': 'Previous',
      'done': 'Done',
      'skip': 'Skip',
      'choose_language': 'Choose Your Language',
      'choose_language_desc': 'Select your preferred language to use the app',
      'arabic': 'العربية',
      'english': 'English',
      'continue': 'Continue',

      // ── Login ──
      'login_biometric': 'Login with Biometric',
      'login_error': 'Invalid login credentials',
      'connection_error': 'Connection error',
      'enter_username_password': 'Please enter username and password',
      'stay_logged_in_desc': 'Account stays open for 72 hours or until logout',
      'forgot_password_desc': 'Please contact your HR manager to reset your password.',

      // ── Dashboard ──
      'dashboard': 'Dashboard',
      'quick_management': 'Quick Management',
      'tools': 'Tools',
      'pending_requests': 'Pending Requests',
      'attendance_today': 'Today\'s Attendance',
      'field_workers': 'Field Workers',
      'live_locations': 'Live Locations',
      'employees': 'Employees',
      'add_employee': 'Add Employee',
      'announcements': 'Announcements',
      'reports': 'Reports',
      'payroll': 'Payroll',
      'reminders': 'Reminders',
      'company_charter': 'Company Charter',
      'geofence': 'Geofence',
      'missions': 'Missions',
      'company_info': 'Company Info',
      'org_tree': 'Org Chart',
      'location_report': 'Location Report',

      // ── Attendance ──
      'check_in': 'Check In',
      'check_out': 'Check Out',
      'checked_in': 'Checked In',
      'checked_out': 'Checked Out',
      'check_in_time': 'Check-in Time',
      'check_out_time': 'Check-out Time',
      'shift': 'Shift',
      'remaining_time': 'Remaining Time',
      'shift_ended': 'Shift ended, you can check out',
      'history': 'Previous Days',
      'today': 'Today',
      'date': 'Date',
      'time': 'Time',
      'early_leave_permission': 'You have early leave permission',
      'attendance_done': 'Attendance recorded successfully',
      'great_work': 'Great work today 👏',

      // ── Employee ──
      'employee_code': 'Employee Code',
      'full_name': 'Full Name',
      'first_name': 'First Name',
      'last_name': 'Last Name',
      'middle_name': 'Middle Name',
      'first_name_ar': 'First Name (Arabic)',
      'last_name_ar': 'Last Name (Arabic)',
      'first_name_en': 'First Name (English)',
      'last_name_en': 'Last Name (English)',
      'phone': 'Phone',
      'email': 'Email',
      'national_id': 'National ID',
      'birth_date': 'Birth Date',
      'gender': 'Gender',
      'male': 'Male',
      'female': 'Female',
      'address': 'Address',
      'branch': 'Branch',
      'department': 'Department',
      'job_title': 'Job Title',
      'direct_manager': 'Direct Manager',
      'hire_date': 'Hire Date',
      'basic_salary': 'Basic Salary',
      'reset_password': 'Reset Password',
      'create_employee': 'Create Employee',
      'edit_employee': 'Edit Employee',
      'employee_details': 'Employee Details',
      'transfer_employee': 'Transfer Employee',
      'employees_list': 'Employees List',
      'no_employees': 'No employees found',

      // ── Status ──
      'active': 'Active',
      'on_leave': 'On Leave',
      'suspended': 'Suspended',
      'resigned': 'Resigned',
      'terminated': 'Terminated',
      'required': 'Required',
      'pending': 'Pending',
      'approved': 'Approved',
      'rejected': 'Rejected',
      'cancelled': 'Cancelled',
      'in_progress': 'In Progress',
      'completed': 'Completed',

      // ── Requests & Leaves ──
      'requests': 'Requests',
      'leaves': 'Leaves',
      'my_requests': 'My Requests',
      'my_leaves': 'My Leaves',
      'submit_request': 'Submit Request',
      'request_type': 'Request Type',
      'leave_type': 'Leave Type',
      'request_title': 'Request Title',
      'request_details': 'Details',
      'from_date': 'From Date',
      'to_date': 'To Date',
      'reason': 'Reason',
      'cancel_request': 'Cancel Request',
      'cancel_request_confirm': 'Are you sure you want to cancel this request?',
      'cancel_reason': 'Cancel Reason (optional)',
      'no_requests': 'No requests found',
      'request_leave': 'Request Leave',
      'leave_balance': 'Remaining Balance',
      'days': 'days',
      'hours': 'hours',
      'amount': 'Amount',

      // ── Missions ──
      'mission': 'Mission',
      'missions_list': 'Missions List',
      'create_mission': 'Create New Mission',
      'mission_title': 'Mission Title',
      'mission_details': 'Mission Details',
      'mission_location': 'Mission Location',
      'client_name': 'Client Name',
      'client_phone': 'Client Phone',
      'priority': 'Priority',
      'urgent': 'Urgent',
      'high': 'High',
      'normal': 'Normal',
      'planned_start': 'Planned Start Time',
      'planned_end': 'Planned End Time',
      'start_mission': 'Start Mission',
      'end_mission': 'End Mission',
      'accept_mission': 'Accept',
      'reject_mission': 'Reject',
      'my_missions': 'My Missions',
      'no_missions': 'No missions found',
      'mission_feedback': 'Visit Feedback',
      'write_feedback': 'Write Feedback',
      'interest_rating': 'Interest Rating',
      'deal_probability': 'Deal Probability',
      'client_status': 'Client Status',
      'very_interested': 'Very Interested',
      'interested': 'Interested',
      'thinking': 'Thinking',
      'not_interested': 'Not Interested',
      'postponed': 'Postponed',
      'needs_followup': 'Needs Follow-up',
      'contract_signed': 'Contract Signed',
      'participants': 'Participants',
      'mission_lead': 'Mission Lead',
      'withdraw_request': 'Withdraw Request',
      'withdraw_reason': 'Withdrawal Reason',

      // ── Notifications ──
      'notifications': 'Notifications',
      'no_notifications': 'No notifications',
      'mark_all_read': 'Mark all as read',
      'now': 'Now',
      'minutes_ago': '{n} minutes ago',
      'hours_ago': '{n} hours ago',
      'days_ago': '{n} days ago',

      // ── Settings ──
      'profile': 'Profile',
      'change_password': 'Change Password',
      'current_password': 'Current Password',
      'new_password': 'New Password',
      'confirm_password': 'Confirm Password',
      'password_changed': 'Password changed successfully',
      'password_mismatch': 'Passwords do not match',
      'password_too_short': 'Password must be at least 6 characters',
      'biometric_login': 'Biometric Login',
      'biometric_confirm': 'Confirm biometric activation',
      'biometric_prompt': 'Sign in with biometric',

      // ── Company ──
      'company': 'Company',
      'company_name': 'Company Name',
      'company_info': 'Company Info',
      'company_logo': 'Company Logo',
      'company_address': 'Company Address',
      'company_phone': 'Company Phone',
      'company_email': 'Company Email',
      'branches': 'Branches',
      'departments': 'Departments',
      'managers': 'Managers',
      'upload_logo': 'Upload Logo',
      'edit_company': 'Edit Company Info',

      // ── Reports ──
      'attendance_report': 'Attendance Report',
      'leaves_report': 'Leaves Report',
      'late_report': 'Late Report',
      'absence_report': 'Absence Report',
      'work_hours_report': 'Work Hours Report',
      'requests_report': 'Requests Report',
      'location_report': 'Location Report',
      'export_pdf': 'Export PDF',
      'export_excel': 'Export Excel',
      'print': 'Print',
      'powered_by': 'Powered by MotionHR - JS Solutions',
    },
  };

  static String get(String key) {
    final lang = LanguageService.currentLanguage;
    return _tr[lang]?[key] ?? _tr['ar']?[key] ?? key;
  }

  static String tr(String key) => get(key);

  static String trWith(String key, Map<String, String> params) {
    String text = get(key);
    params.forEach((k, v) => text = text.replaceAll('{$k}', v));
    return text;
  }
}